### ISSUE TITLE
样式建议

### ISSUE THREAD

**Issue by JingHai-Lingyun** [GmeroAlert/GmAlert#4]
组件很好用，不过对于样式，想提出以下两点建议
增加夜间（Dark Theme）样式
提供一个可自定义的位置（例如使用 CSS 变量，JS变量(bundle)等）来调整组件中颜色，以适配自己的网站

**Comment by g-mero** [comment]
你可以参考css文件，我们提供了一些css变量来控制颜色，夜间模式我们暂时是交由用户自行配置css变量实现（该方法也适用于bundle）。可以参考以下css代码

``` css
[data-theme="dark"] .gmal {
  --gmal-bg: #303030;
  --gmal-text: #afafaf;
  --gmal-border: 1px solid #535353;
  --gmal-light: #535353;
  --gmal-shadow: rgb(255 255 255 / 10%);
}
```
